### ISSUE TITLE
[문의] 맥 지원

### ISSUE THREAD

**Issue by ShawnBaek** [pronist/tistory-backup#1]
티스토리 백업 관련 프로그램 찾다가 왔습니다.

좋은 어플 만들어주셔서 감사합니다.

혹시 맥도 지원해주실 수 있나요?

감사합니다 👍

**Comment by pronist** [comment]
@ShawnBaek 앗, 저 사실 윈도우만 써서 맥으로 빌드 안해 봤..  ㅋㅋㅋㅋㅋ :(
