### ISSUE TITLE
특정 글의 사진이 백업되지 않습니다.

### ISSUE THREAD

**Issue by minikupa** [pronist/tistory-backup#2]
다른 글들을 정상적으로 백업이 되는데 프로그램의 문제인지, 티스토리 api 문제인진 모르겠으나 일부 특정 글의 사진이 백업과정에서 누락됩니다. 몇 번을 반복해도 특정 글은 계속 사진이 백업되지 않네요.

**Comment by pronist** [comment]
@minikupa 카카오에서 제공하는 티스토리 API 에 이미지 경로가 부정확해서 임의로 변경해서 처리하고 있기에 일부 이미지가 누락될 수 있습니다. 티스토리 API 에서 **올바른 데이터를 제공하지 않고 있기 때문**인지라 해당 데이터를 기반으로 하는 **사용자 어플리케이션 단에서 건드릴 수 없는 부분**입니다. 카카오 측에서 데이터를 올바르게 적용할 때까지 기다리는 수 밖에는 없습니다.
