### ISSUE TITLE
맥 오류

### ISSUE THREAD

**Issue by hoony6134** [pronist/tistory-backup#4]
![image](https://user-images.githubusercontent.com/65375075/106976477-d2410380-679b-11eb-95c5-47fdf83186b9.png)
맥 경우 이렇게 뜹니다

**Comment by hoony6134** [comment]
@pronist

**Comment by pronist** [comment]
@hoony6134 답은 너무 늦게드렸군요. 현재 맥의 경우 **기여**를 통해 받은 것이라 저로서는 해결하지 어려운 부분임을 먼저 말씀드립니다. (윈도우 유저는 웁니다 ㅜㅜ ) 그러나, 맥에서의 오류 발생부분은 사실일 것이기 때문에 이슈는 남겨두도록 하겠습니다.
